# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYnu1hq37ny-zu35T0MyInH4KNa4QA-h
"""

import tensorflow as tf
import cv2
import pathlib
import os
import numpy as np
import random
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

import seaborn as sns

"""Download and Extract Dataset"""

import tensorflow as tf
import pathlib
import tarfile
import os

# Dataset URL
dataset_url = "https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz"

# Download the dataset
archive = tf.keras.utils.get_file(
    "flower_photos.tgz",
    origin=dataset_url
)

# Extract dataset manually
extract_path = "/content/flowers"

with tarfile.open(archive, "r:gz") as tar:
    tar.extractall("/content")

# Correct dataset path
data_dir = pathlib.Path("/content/flower_photos")

print("Dataset exists:", data_dir.exists())
print("Dataset path:", data_dir)

"""Explore Dataset Classes"""

classes = sorted([
    folder.name
    for folder in data_dir.iterdir()
    if folder.is_dir()
])

print("Classes:", classes)
print("Number of classes:", len(classes))

"""Count Images per Class

"""

for class_name in classes:
    class_path = data_dir / class_name
    images_count = len(list(class_path.glob("*")))

    print(class_name, ":", images_count, "images")

"""Load and Preprocess Images"""

IMAGE_SIZE = (128, 128)

images = []
labels = []

for label, class_name in enumerate(classes):

    class_path = data_dir / class_name

    for image_path in class_path.glob("*"):

        image = cv2.imread(str(image_path))

        if image is None:
            continue

        image = cv2.resize(image, IMAGE_SIZE)

        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        images.append(image)
        labels.append(label)

X = np.array(images)
y = np.array(labels)

print("Images shape:", X.shape)
print("Labels shape:", y.shape)

"""Shuffle the Dataset"""

combined = list(zip(X, y))

random.shuffle(combined)

X, y = zip(*combined)

X = np.array(X)
y = np.array(y)

print("Data shuffled successfully!")

"""Split Data into Training and Validation Sets"""

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training images:", len(X_train))
print("Validation images:", len(X_val))

"""Normalize the Images"""

X_train = X_train.astype("float32") / 255.0
X_val = X_val.astype("float32") / 255.0

print("Normalization completed!")

"""Build the MLP Model

"""

num_classes = len(classes)

model = tf.keras.Sequential([

    tf.keras.layers.Flatten(
        input_shape=(128, 128, 3)
    ),

    tf.keras.layers.Dense(
        512,
        activation="relu"
    ),

    tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(
        256,
        activation="relu"
    ),

    tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(
        128,
        activation="relu"
    ),

    tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(
        num_classes,
        activation="softmax"
    )
])

model.summary()

"""Compile the Model"""

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("Model compiled successfully!")

"""Train the Model"""

history = model.fit(
    X_train,
    y_train,
    epochs=15,
    batch_size=32,
    validation_data=(X_val, y_val)
)

print("Final Training Accuracy:",
      history.history["accuracy"][-1])

print("Final Validation Accuracy:",
      history.history["val_accuracy"][-1])

"""Evaluate the Model"""

loss, accuracy = model.evaluate(
    X_val,
    y_val,
    verbose=1
)

print("Validation Loss:", loss)
print("Validation Accuracy:", accuracy)

"""Plot Training and Validation Accuracy"""

#accuracy
plt.figure(figsize=(8, 5))

plt.plot(
    history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")

plt.legend()
plt.show()

"""Plot Training and Validation Loss"""

#loss
plt.figure(figsize=(8, 5))

plt.plot(
    history.history["loss"],
    label="Training Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")

plt.legend()
plt.show()

"""Classification Report"""

y_pred_probability = model.predict(X_val)

y_pred = np.argmax(
    y_pred_probability,
    axis=1
)

print(
    classification_report(
        y_val,
        y_pred,
        target_names=classes
    )
)

"""Confusion Matrix"""

cm = confusion_matrix(
    y_val,
    y_pred
)

plt.figure(figsize=(8, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=classes,
    yticklabels=classes
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

"""Upload a New Image"""

from google.colab import files

uploaded = files.upload()

"""Flower Type Prediction"""

image_path = list(uploaded.keys())[0]

image = cv2.imread(image_path)

image = cv2.resize(image, IMAGE_SIZE)

image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

image = image.astype("float32") / 255.0

image = np.expand_dims(image, axis=0)

prediction = model.predict(image)

predicted_index = np.argmax(prediction[0])

predicted_class = classes[predicted_index]

confidence = prediction[0][predicted_index] * 100

print("Predicted Flower:", predicted_class)
print("Confidence:", round(confidence, 2), "%")

"""Save the Trained Model"""

model.save("/content/flower_mlp_model.h5")

print("Model saved successfully!")

"""Build the CNN Model"""

num_classes = len(classes)

model = tf.keras.Sequential([

    # Convolutional Layer 1
    tf.keras.layers.Conv2D(
        32,
        (3, 3),
        activation="relu",
        input_shape=(128, 128, 3)
    ),

    tf.keras.layers.MaxPooling2D(
        (2, 2)
    ),

    # Convolutional Layer 2
    tf.keras.layers.Conv2D(
        64,
        (3, 3),
        activation="relu"
    ),

    tf.keras.layers.MaxPooling2D(
        (2, 2)
    ),

    # Convolutional Layer 3
    tf.keras.layers.Conv2D(
        128,
        (3, 3),
        activation="relu"
    ),

    tf.keras.layers.MaxPooling2D(
        (2, 2)
    ),

    # Flatten
    tf.keras.layers.Flatten(),

    # Fully Connected Layer
    tf.keras.layers.Dense(
        128,
        activation="relu"
    ),

    tf.keras.layers.Dropout(0.5),

    # Output Layer
    tf.keras.layers.Dense(
        num_classes,
        activation="softmax"
    )
])

model.summary()

"""Compile the CNN Model"""

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("CNN model compiled successfully!")

"""Train the CNN Model"""

history = model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_val, y_val)
)

"""Check Model Accuracy"""

print("Final Training Accuracy:",
      history.history["accuracy"][-1])

print("Final Validation Accuracy:",
      history.history["val_accuracy"][-1])

"""Evaluate the Model"""

loss, accuracy = model.evaluate(
    X_val,
    y_val,
    verbose=1
)

print("Validation Loss:", loss)
print("Validation Accuracy:", accuracy)

""". Plot Training and Validation Accuracy"""

plt.figure(figsize=(8, 5))

plt.plot(
    history.history["accuracy"],
    label="Training Accuracy"
)

plt.plot(
    history.history["val_accuracy"],
    label="Validation Accuracy"
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("Training vs Validation Accuracy")

plt.legend()
plt.show()

"""Plot Training and Validation Loss"""

plt.figure(figsize=(8, 5))

plt.plot(
    history.history["loss"],
    label="Training Loss"
)

plt.plot(
    history.history["val_loss"],
    label="Validation Loss"
)

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")

plt.legend()
plt.show()

"""Classification Report"""

y_pred_probability = model.predict(X_val)

y_pred = np.argmax(
    y_pred_probability,
    axis=1
)

print(
    classification_report(
        y_val,
        y_pred,
        target_names=classes
    )
)

"""Confusion Matrix"""

cm = confusion_matrix(
    y_val,
    y_pred
)

plt.figure(figsize=(8, 6))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=classes,
    yticklabels=classes
)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()

"""Upload a New Image"""

from google.colab import files

uploaded = files.upload()

"""Flower Type Prediction"""

image_path = list(uploaded.keys())[0]

image = cv2.imread(image_path)

image = cv2.resize(
    image,
    IMAGE_SIZE
)

image = cv2.cvtColor(
    image,
    cv2.COLOR_BGR2RGB
)

image = image.astype("float32") / 255.0

image = np.expand_dims(
    image,
    axis=0
)

prediction = model.predict(image)

predicted_index = np.argmax(
    prediction[0]
)

predicted_class = classes[predicted_index]

confidence = prediction[0][predicted_index] * 100

print("Predicted Flower:", predicted_class)
print("Confidence:", round(confidence, 2), "%")

"""Save the Trained Model"""

model.save("/content/flower_cnn_model.h5")

print("CNN model saved successfully!")

"""CNN Improved Model"""

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomFlip("horizontal"),
    tf.keras.layers.RandomRotation(0.1),
    tf.keras.layers.RandomZoom(0.1)
])

model_improved = tf.keras.Sequential([

    data_augmentation,

    tf.keras.layers.Conv2D(
        32, (3, 3),
        activation="relu",
        input_shape=(128, 128, 3)
    ),
    tf.keras.layers.MaxPooling2D((2, 2)),

    tf.keras.layers.Conv2D(
        64, (3, 3),
        activation="relu"
    ),
    tf.keras.layers.MaxPooling2D((2, 2)),

    tf.keras.layers.Conv2D(
        128, (3, 3),
        activation="relu"
    ),
    tf.keras.layers.MaxPooling2D((2, 2)),

    tf.keras.layers.Flatten(),

    tf.keras.layers.Dense(
        128,
        activation="relu"
    ),

    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Dense(
        num_classes,
        activation="softmax"
    )
])

model_improved.summary()

"""Compile"""

model_improved.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

"""Early Stopping"""

early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=4,
    restore_best_weights=True
)

"""Training"""

history_improved = model_improved.fit(
    X_train,
    y_train,
    epochs=30,
    batch_size=32,
    validation_data=(X_val, y_val),
    callbacks=[early_stopping]
)

print(
    "Final Training Accuracy:",
    history_improved.history["accuracy"][-1]
)

print(
    "Final Validation Accuracy:",
    history_improved.history["val_accuracy"][-1]
)

image_path = list(uploaded.keys())[0]

image = cv2.imread(image_path)

image = cv2.resize(image, IMAGE_SIZE)

image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

image = image.astype("float32") / 255.0

image = np.expand_dims(image, axis=0)

prediction = model_improved.predict(image)

predicted_index = np.argmax(prediction[0])

predicted_class = classes[predicted_index]

confidence = prediction[0][predicted_index] * 100

print("Predicted Flower:", predicted_class)
print("Confidence:", round(confidence, 2), "%")

"""Build Transfer Learning Model"""

base_model = tf.keras.applications.MobileNetV2(
    input_shape=(128, 128, 3),
    include_top=False,
    weights="imagenet"
)

# Freeze the pretrained layers
base_model.trainable = False

model_transfer = tf.keras.Sequential([

    base_model,

    tf.keras.layers.GlobalAveragePooling2D(),

    tf.keras.layers.Dropout(0.4),

    tf.keras.layers.Dense(
        128,
        activation="relu"
    ),

    tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(
        num_classes,
        activation="softmax"
    )
])

model_transfer.summary()

"""Compile Transfer Learning Model"""

model_transfer.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("Transfer Learning model compiled successfully!")

"""Train Transfer Learning Model"""

history_transfer = model_transfer.fit(
    X_train,
    y_train,
    epochs=15,
    batch_size=32,
    validation_data=(X_val, y_val),
    callbacks=[early_stopping]
)

"""Check Accuracy"""

print(
    "Final Training Accuracy:",
    history_transfer.history["accuracy"][-1]
)

print(
    "Final Validation Accuracy:",
    history_transfer.history["val_accuracy"][-1]
)

"""Evaluate"""

loss_transfer, accuracy_transfer = model_transfer.evaluate(
    X_val,
    y_val,
    verbose=1
)

print("Transfer Learning Validation Accuracy:",
      accuracy_transfer)

"""test"""

image_path = list(uploaded.keys())[0]

image = cv2.imread(image_path)

image = cv2.resize(image, IMAGE_SIZE)

image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

image = image.astype("float32") / 255.0

image = np.expand_dims(image, axis=0)

prediction = model_transfer.predict(image)

predicted_index = np.argmax(prediction[0])

predicted_class = classes[predicted_index]

confidence = prediction[0][predicted_index] * 100

print("Predicted Flower:", predicted_class)
print("Confidence:", round(confidence, 2), "%")

"""Compare Models"""

# Model Accuracy Comparison

mlp_accuracy = 0.41416892409324646
cnn_accuracy = 0.7084468603134155
improved_cnn_accuracy = 0.7588555812835693
transfer_accuracy = accuracy_transfer

models = [
    "MLP",
    "CNN",
    "Improved CNN",
    "MobileNetV2"
]

accuracies = [
    mlp_accuracy,
    cnn_accuracy,
    improved_cnn_accuracy,
    transfer_accuracy
]

print("Model Performance Comparison")
print("-" * 40)

for model_name, accuracy in zip(models, accuracies):
    print(
        f"{model_name}: {accuracy * 100:.2f}%"
    )

best_index = np.argmax(accuracies)

print("-" * 40)
print(
    "Best Model:",
    models[best_index]
)

print(
    "Best Validation Accuracy:",
    f"{accuracies[best_index] * 100:.2f}%"
)

plt.figure(figsize=(10, 6))

plt.bar(
    models,
    [accuracy * 100 for accuracy in accuracies]
)

plt.xlabel("Models")
plt.ylabel("Validation Accuracy (%)")
plt.title("Model Performance Comparison")

plt.ylim(0, 100)

plt.show()

